### ISSUE TITLE
Counting all the elements of a large collection is breaking

### ISSUE THREAD

**Issue by adriasala124** [HPInc/davinci#121]
# Summary
While migrating the ship-api to DaVinci we discovered that trying to list all the shipments was timing out. 
The problem seems to be coming from trying to get an exact count of the documents in a very large collection in [this line](https://github.com/HPInc/davinci/blob/ef66ca147921aebfe4a67af3908d9567e59111cd/packages/mongoose/src/createMongooseController.ts#L187).
According to mongoose's [documentation](https://mongoosejs.com/docs/api.html#model_Model.countDocuments), the countDocuments method doesn't use any index, and it suggests to user estimatedDocumentCount() for large collections.
# Problems
* Using an estimated document count could break pagination -> This could be acceptable for very large collections where it is very unlikely that anyone will get to the last page. A possible solution could be to enable/disable the estimated count through the configuration.
* Previously, of-base-api was using a mongoose plugin to handle pagination ([feathers-mongoose](https://www.npmjs.com/package/feathers-mongoose)). Using a plugin could be another solution.

**Comment by juanjoseruiz** [comment]
@pierissimo could you please have a look when you have some time? @adriasala124 encountered this issue when migrating ship-api to DaVinci. We think the same may be happening in pimienta-api (workforce-api uses a different mechanism for pagination and always limits to 1000 elements)

**Comment by juanjoseruiz** [comment]
Yep, digging a bit more into the feathers-mongoose current version used in previous api it looks like it is doing this operation for the count:

                this.model.where(where).count().exec()

and according to the documentation, using that without a predicate ( where : {} ) returns an estimate document count.

unsure if we can use that condition to choose one method or the other, probably we need to do some more testing @adriasala124

**Comment by juanjoseruiz** [comment]
Fixed in #122

**Comment by pierissimo** [comment]
As discussed in the PR, estimatedDocumentCount() does not accept a filter criteria and that partially defeats the purpose of the change, as we rarely request the count of the entire collection, not even filtering by the organization ID.

Another approach would be to set the upper bound limit when counting:
`model.find(where).limit(10000).exec();`

**Comment by adriasala124** [comment]
A limit is already set in DaVinci's code [here](https://github.com/HPInc/davinci/blob/82a78baa9e0f86f8d089cf61691b918a0a713ab1/packages/mongoose/src/createMongooseController.ts#L297).

**Comment by pierissimo** [comment]
sorry I've fixed the example query of my [previous comment](https://github.com/HPInc/davinci/issues/121#issuecomment-1157306947), including the `.count()`.
This is the way it works in the workforce-api

**Comment by juanjoseruiz** [comment]
Yes, we explored to do in that way. As you said is not so common to request the count of the entire collection (in this case it was an internal API call), but decided to go with the estimated as the behavior was less breaking (it should behave very similar as previous implementation)

**Comment by pierissimo** [comment]
Yeah, I agree that is probably a separate problem.
Thanks
