### ISSUE TITLE
Entity definition broken

### ISSUE THREAD

**Issue by juanjoseruiz** [HPInc/davinci#258]
Upgrading DaVinci reflector to latest version [@davinci/reflector@2.3.0](https://github.com/HPInc/davinci/releases/tag/%40davinci%2Freflector%402.3.0) is throwing an exception when starting the API:

```
{"name":"app","error":{},"msg":"Fatal error during module registration"}
/.../node_modules/@davinci/core/src/entity/EntityDefinition.ts:281
                return reflection.decorators.find(d => d[DecoratorId] === 'entity');
                               ^
TypeError: Cannot read properties of undefined (reading 'find')
```
Looks like this started happening since this upgrade to @plumier/refect:

https://github.com/HPInc/davinci/pull/230

We tracked the release of plumier that starts to fail, and the code is working if we downgrade to 1.0.6 and starts to fail if we use 1.1.0:

https://github.com/plumier/plumier/releases/tag/v1.1.0

**Comment by juanjoseruiz** [comment]
@pierissimo FYI, we will try to have a look at the needed changes to adapt to the latest version of plumier in the following weeks. Another option is to downgrade to the previous one, but not sure if we will be missing something.

**Comment by pierissimo** [comment]
hey Juanjo, are you able to reproduce the issue in a blank project?
I've put together [this starter on Stackblitz](https://stackblitz.com/edit/davinci-starter?file=src%2Findex.ts), hopefully can facilitate it

**Comment by juanjoseruiz** [comment]
Hey @pierissimo I was digging a bit more and the issue seems to be related with defining a property in the schema with the type: Schema.Types.Mixed (from mongoose).

In the example provided, it's just enough with importing mongoose (5.x is fine) and add a new property to one of the schemas:

`  @entity.prop({ type: Schema.Types.Mixed })
  attributes?: unknown;
`

You can find the updated [Stackblitz here](https://stackblitz.com/edit/davinci-starter-qwgwsk?file=src%2Fapi%2Fcustomer%2Fcustomer.schema.ts)

**Comment by pierissimo** [comment]
hey Juanjo, in the real API, is `Schema.Types.Mixed` passed as explicit type to the @mgoose.prop() decorator? Or to the `@entity.prop()`?

**Comment by pierissimo** [comment]
ok, in that case, a better definition would look like this:
```
@mgoose.prop({ type: Schema.Types.Mixed })
@entity.prop()
attributes: object;
```

Anyway, I'm putting together another example that showcases better the issue

**Comment by juanjoseruiz** [comment]
Great, thanks, I also realized the same is happening for properties defined with this type:

`
@mgoose.prop({ type: Schema.Types.ObjectId })
@entity.prop({ type: Schema.Types.ObjectId })
`

If I update both to @entity.prop(), the API seems to start successfully.

So, do you recommend to update the code? Or do you consider this still an issue?

Thanks!

**Comment by pierissimo** [comment]
For correctness, I'd suggest you to update your code.
Passing a mongoose artefact to the @entity.prop() decorator doesn't make much sense.

But in the meantime I'll try to get to the root cause, it shouldn't take long

**Comment by pierissimo** [comment]
@juanjoseruiz, as you can see [here](https://stackblitz.com/edit/davinci-starter-akjcta?file=src%2Findex.ts), the reflection result of a function doesn't contain the `decorators` property, as it's not possible to decorate simple functions (only class methods).

A simple solution is to use the optional chaining operator. I'll put together a draft PR shortly

**Comment by pierissimo** [comment]
opened a [draft PR](https://github.com/HPInc/davinci/pull/259), please have a look and add more tests if necessary

**Comment by juanjoseruiz** [comment]
Thanks @pierissimo I approved it, I think the test you already added should cover all cases

**Comment by juanjoseruiz** [comment]
@pierissimo fixed in https://github.com/HPInc/davinci/pull/259 so closing accordingly.

Thanks for your help! I'll update either our code & DaVinci version to the newest one.
