### ISSUE TITLE
Ability to include 'example' on OpenAPI docs

### ISSUE THREAD

**Issue by thekiwi** [HPInc/davinci#33]
I would like to be able to include example values on the generated OpenAPI docs:
https://swagger.io/specification/#example-object

I imagine it would look something like this:
```TypeScript
@openapi.definition({ title: 'SomeRequest' })
class SomeRequest {
	@openapi.prop({ required: true, example: 'eu-west-1' })
	region: string;
}
```

**Comment by pierissimo** [comment]
implemented in the last DaVinci version
