### ISSUE TITLE
Maximum request json limit size 1MB

### ISSUE THREAD

**Issue by DanilaFadeev** [HPInc/davinci#63]
There is a static limit for `1MB` of request JSON payload, configured with express middleware. Is it possible to add some framework option to affect this default value? [Source](https://github.com/HPInc/davinci/blob/master/packages/core/src/createApp.ts#L78)

Something like this, for instance:
```ts
interface DaVinciOptions {
    ...
    express: {
        json: OptionsJson;
        urlencoded: OptionsUrlencoded;
    }
}
```

**Comment by juanjoseruiz** [comment]
Implemented as part of DaVinci 2.1, now it is possible to pass a custom httpserver (express or fastify) instance preconfigured.
