### ISSUE TITLE
Unable to create https Server

### ISSUE THREAD

**Issue by jferrerol** [HPInc/davinci#88]
I would like to know if there is any way to create a https server with Davinci.

**Comment by pierissimo** [comment]
Hey Jorge, you can create a https server by adding the https server initialization code, in your application `app.ts` file:
```ts
if (require.main === module) {
	expressApp.start();
	const httpsServer = https.createServer({key: key, cert: cert }, expressApp);
        httpsServer.listen(YOUR_PORT_NUMBER_HERE)
}
```

**Comment by jferrerol** [comment]
> Hey Jorge, you can create a https server by adding the https server initialization code, in your application `app.ts` file:
> 
> ```ts
> if (require.main === module) {
> 	expressApp.start();
> 	const httpsServer = https.createServer({key: key, cert: cert }, expressApp);
>         httpsServer.listen(YOUR_PORT_NUMBER_HERE)
> }
> ```

Thanks!
